[2022-06-05 00:40:22,341] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: census.populate_table scheduled__2022-06-05T03:39:05.999952+00:00 [queued]>
[2022-06-05 00:40:22,361] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: census.populate_table scheduled__2022-06-05T03:39:05.999952+00:00 [queued]>
[2022-06-05 00:40:22,361] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-06-05 00:40:22,361] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-06-05 00:40:22,361] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-06-05 00:40:22,391] {taskinstance.py:1378} INFO - Executing <Task(PythonOperator): populate_table> on 2022-06-05 03:39:05.999952+00:00
[2022-06-05 00:40:22,403] {standard_task_runner.py:52} INFO - Started process 29748 to run task
[2022-06-05 00:40:22,409] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'census', 'populate_table', 'scheduled__2022-06-05T03:39:05.999952+00:00', '--job-id', '757', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp9rs5fdr1', '--error-file', '/tmp/tmpgott_m76']
[2022-06-05 00:40:22,410] {standard_task_runner.py:80} INFO - Job 757: Subtask populate_table
[2022-06-05 00:40:22,507] {task_command.py:370} INFO - Running <TaskInstance: census.populate_table scheduled__2022-06-05T03:39:05.999952+00:00 [running]> on host uiliam-Vostro-15-3515
[2022-06-05 00:40:22,629] {taskinstance.py:1570} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=census
AIRFLOW_CTX_TASK_ID=populate_table
AIRFLOW_CTX_EXECUTION_DATE=2022-06-05T03:39:05.999952+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-05T03:39:05.999952+00:00
[2022-06-05 00:40:22,635] {logging_mixin.py:115} INFO - <_io.TextIOWrapper name='teste_uiliam.csv' mode='r' encoding='UTF-8'>
[2022-06-05 00:40:23,011] {python.py:173} INFO - Done. Returned value was: None
[2022-06-05 00:40:23,036] {taskinstance.py:1396} INFO - Marking task as SUCCESS. dag_id=census, task_id=populate_table, execution_date=20220605T033905, start_date=20220605T034022, end_date=20220605T034023
[2022-06-05 00:40:23,101] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-05 00:40:23,168] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
